webtalk_init -webtalk_dir /home/stefan/Downloads/RV32I_pipelined/RV32I/RISCV_project/RISCV_project.sim/sim_1/behav/xsim/xsim.dir/TOP_RISCV_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Apr 22 15:52:39 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "35c81648-1ef0-4e05-a933-867dedf82756" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "a4842cd3de00462e919beef1e592df11" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "24" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 22.04.4 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 5700U with Radeon Graphics" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1877.101 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "6.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "2176987600 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "50.32_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "123372_KB" -context "xsim\\usage"
webtalk_transmit -clientid 354601470 -regid "" -xml /home/stefan/Downloads/RV32I_pipelined/RV32I/RISCV_project/RISCV_project.sim/sim_1/behav/xsim/xsim.dir/TOP_RISCV_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/stefan/Downloads/RV32I_pipelined/RV32I/RISCV_project/RISCV_project.sim/sim_1/behav/xsim/xsim.dir/TOP_RISCV_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/stefan/Downloads/RV32I_pipelined/RV32I/RISCV_project/RISCV_project.sim/sim_1/behav/xsim/xsim.dir/TOP_RISCV_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
